### ISSUE TITLE
Is it possible to add a ros wrapper?

### ISSUE THREAD

**Issue by LiShuaixin** [jbehley/SuMa#18]
HI @jbehley , thanks a lot for sharing this great work! I tested it using KITTI. The visualization of point cloud  result is good. 

Then I tried to write a ros warper for SuMa, so as to test it on real robots/cars with a 3D lidar. Just like what is used in the qt wrapper `/visualizer/VisualizerWindow.cpp` and implementation `/visualizer/visualizer.cpp`, I create a class `SuMaRosWarper` with a member of `std::shared_ptr<SurfelMapping> fusion_`,  then created a `std::shared_ptr<SurfelMapping>` pointer to initialize it. However, a segment fault was thrown in the construction of `SurfelMapping`. I backtraced the code and found the error occurred when called `glGenBuffers(1, &id_);`:

![2019-09-27 16-34-35屏幕截图](https://user-images.githubusercontent.com/22472452/65755306-6f6e3f80-e145-11e9-9a98-45ef3a76e42d.png)

BUT I can run your qt version smoothly. What's wrong with this? any suggestion?

**Comment by jbehley** [comment]
Since SuMa uses OpenGL for computation, you always need a opengl context in the same (!) thread. Updates and everything must also happen in this thread.

With ROS you have to take into account that nodes might not run on the same thread.

See for instance `glow::X11OffscreenContext` for a headless/windowless context.

But with this you still need a X server running. A true X free context you could get with EGL.

**Comment by LiShuaixin** [comment]
Thanks a lot!

**Comment by LiShuaixin** [comment]
Hi, @jbehley  Do you think it's possible to use ros rviz to create a opengl context for SuMa?

**Comment by jbehley** [comment]
If you manage to run it in the same thread, then it could work. But I never
tried this. So no guarantees.

**Comment by MohamedAfifii** [comment]
@LiShuaixin Were you able to use rviz with suma?
