### ISSUE TITLE
Question regarding merging 3 VLP-16 

### ISSUE THREAD

**Issue by ArghyaChatterjee** [jbehley/SuMa#33]
Hello, I am working with a setup which merges 3 VLP-16 together and publishes the combined point cloud w.r.t baselink. Among the 3 llidars. one is placed horizontally and other 2 are tilted at a certain angle. So I was wondering what things I have to change inside `config/vlp16_example.xml` file. 
N.B: When I imported my combined point cloud data with vlp16_example.xml file, it was looking good. I can see the point clouds and the rings generated by 3 different pointclouds well. Though it looks satisfactory visually, I wanted to reassure that I am not loosing any pointcloud data after importing inside SuMa.

**Comment by jbehley** [comment]
the raw point clouds should be okay. but the projection (a spherical projection) is definitely wrong and not what you want in the end. In SuMa, we assume that we can get a relatively dense projection of a single point cloud by generating a range-image-like representation. In your case, the horizontal sensor will generate this, but the other sensor will probably not be accounted for. Thus, regarding your questions: while the point cloud in the visualizer looks complete, the projection will not account for all points that are available. (While SuMa might still work, but not use all available information.)

You could try what happens if you increase the vertical field of view to also get lidar returns for the tilted sensors, but it seems not optimal to do it in that way. Technically, you want to account for the rotations for the other sensors and generate for these separate vertex/normal maps and also generate this from the map. However, we do not support this natively, such that you would have to change this.

**Comment by ArghyaChatterjee** [comment]
Thanks for the info. Actually I am just using it to generate the 'poses.txt' file so that I can import the pointclouds inside 'point labeler' in kitti format. I tried top single point cloud, a combined 3 pointcloud and a combined 3 point cloud with filters (downsampled). However, the combined 3 pointcloud performs the best while others perform good (filtered one) and average (single pointcloud).
